version: "3"
services:
    coreDns:
        image: coredns/coredns:1.1.4
        volumes:
          - $PWD:/opt
        network_mode: "host"
        restart: always
        command: ["-conf","/opt/Corefile","-dns.port=53"]
        
    etcd:
        image: quay.io/coreos/etcd:v2.0.0
        network_mode: "host"
        restart: always
        command: ["-listen-peer-urls=http://0.0.0.0:7001,http://0.0.0.0:2380","-listen-client-urls=http://0.0.0.0:4001,http://0.0.0.0:2379"]     
    etcdkeeper:
        build: ./etcdkeeper
        network_mode: "host"
        restart: always
        depends_on:
          - etcd
